image: Visual Studio 2019
branches:
  only:
    - master
    - develop
version: 1.0.0.{build}
clone_depth: 5
init:
- git config --global user.email "chocolatey@realdimensions.net"
- git config --global user.name "Chocolatey yo"
nuget:
  disable_publish_on_pr: true
# See https://www.appveyor.com/docs/build-configuration/#secure-variables
environment:
  COVERALLS_REPO_TOKEN:
    secure: 2HaukGxepJGCR69mwx4u14VaR6p/q6Qdy1+PJmqHoEWGzbI5EfV+s4BaLWAZSk0j
  GITHUB_APIKEY:
    secure: 4O7GRcOJFAK2K+VHtPZVKzqDMfwWrObiu1TAaHay6sUsF5gOBXhDHpz97wXt4jnG
build_script:
- ps: ./build.ps1 'all'
test: off
artifacts:
#- path: build_output\build_artifacts\nunit\index.html
#  name: NUnitResults.html
- path: build_output\build_artifacts\codecoverage\Html\index.htm
  name: OpenCoverResults.htm
#- path: code_drop\build_artifacts\ilmerge\ilmerge.log
#  name: ILMerge.log
#- path: code_drop\build_artifacts\ilmerge\ilmergedll.log
#  name: ILMergeDLL.log
#- path: code_drop\nuget\*.nupkg
notifications:
- provider: Email
  to:
  - tapika@yahoo.com
  subject: AppVeyor - swupd Build Notification
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true
