//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyCompany("Chocolatey")]
[assembly: AssemblyProduct("Chocolatey GUI")]
[assembly: AssemblyVersion("0.19.0.0")]
[assembly: AssemblyFileVersion("0.19.0.0")]
[assembly: AssemblyInformationalVersion("0.19.0")]
[assembly: AssemblyCopyright("Copyright 2014 - Present Rob Reynolds, the maintainers of Chocolatey, and RealDimensions Software, LLC")]

