using System;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;
using System.Security;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(false)]
[assembly: AssemblyCompanyAttribute("Chocolatey Software, Inc.")]
[assembly: AssemblyVersionAttribute("0.10.16.0")]
[assembly: AssemblyFileVersionAttribute("0.10.16.0")]
[assembly: AssemblyInformationalVersionAttribute("0.10.16-beta-140-g2024b18e")]
[assembly: AssemblyTitleAttribute("chocolatey")]
[assembly: AssemblyProductAttribute("chocolatey")]
[assembly: AssemblyDescriptionAttribute("chocolatey is a product of Chocolatey Software, Inc. - All Rights Reserved.")]
[assembly: AssemblyTrademarkAttribute("chocolatey - Chocolatey Software, Inc.")]
[assembly: AssemblyCopyrightAttribute("Copyright © 2017 - 2020 Chocolatey Software, Inc. Copyright © 2011 - 2017, RealDi" +
    "mensions Software, LLC - All Rights Reserved.")]

