name: Swupd Builds

on:
  # Trigger on pushes to master and stable, or with pull requests
  push:
    branches:
    - master
    - stable
    - develop
  pull_request:
    branches:
    - master
    - stable

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  API_KEY: ${{secrets.API_KEY}}
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  COVERALLS_REPO_TOKEN: ${{secrets.COVERALLS_REPO_TOKEN}}
  CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}

jobs:
  # Build using mono on Ubuntu
  #ubuntu-build:
  #  runs-on: ubuntu-latest
  #  steps:
  #  - uses: actions/checkout@v2
  #  - name: Build with Mono
  #    run: |
  #      chmod +x build.sh
  #      $GITHUB_WORKSPACE//build.sh -v
  # Build on Windows
  windows-build:
    runs-on: windows-2019
    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 5

    - name: Github actions environment to local environment
      uses: cake-build/cake-action@v1
      with:
        cake-version: 2.3.0
        script-path: routeenvvar.cake

    - name: Build all
      run: .\cakebuild.bat all
  # Build using mono on MacOS
  #macos-build:
  #  runs-on: macos-latest
  #  steps:
  #   - uses: actions/checkout@v2
  #   - name: Build with Mono
  #     run: |
  #        chmod +x build.sh
  #        $GITHUB_WORKSPACE//build.sh -v
  # Build using Mono in Docker on Ubuntu
  #docker-build:
  #  runs-on: ubuntu-latest
  #  steps:
  #    -
  #      name: Checkout
  #      uses: actions/checkout@v2
  #    -
  #      name: Set up QEMU
  #      uses: docker/setup-qemu-action@v1
  #    -
  #      name: Set up Docker Buildx
  #      uses: docker/setup-buildx-action@v1
  #    -
  #      name: Build and push
  #      uses: docker/build-push-action@v2
  #      with:
  #        context: .
  #        file: docker/Dockerfile.linux
  #        push: false
  #        tags: chocolatey/choco:latest
